/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hn.uth.pa1.parcial2.tarea2.app;

import hn.uth.pa1.parcial2.tarea2.app.objetos.Vehiculo;
import hn.uth.pa1.parcial2.tarea2.app.repositorios.VehiculoRepositorio;
import java.awt.Image;
import java.time.LocalDate;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Miriam
 */
public class FrmCatalogoVehiculos extends javax.swing.JFrame {

    /**
     * Creates new form FrmCatalogoVehiculos
     */
    
    VehiculoRepositorio repo = new VehiculoRepositorio();
    List<Vehiculo> vehiculos;
    
    public FrmCatalogoVehiculos() {
        initComponents();
        try {
            this.vehiculos = repo.buscarTodo();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al bucar todos");
        }
        cargarDatos1(vehiculos.get(0));
        cargarDatos2(vehiculos.get(1));
        cargarDatos3(vehiculos.get(2));
    }

    public void cargarDatos1(Vehiculo vehiculo){
        lblNombre1.setText(vehiculo.getNombre());
        lblMarca1.setText(vehiculo.getMarca());
        lblModelo1.setText(vehiculo.getModelo());
        lblPrecio1.setText(String.valueOf("LSP " + vehiculo.getPrecio()));
        lblAnio1.setText(String.valueOf(vehiculo.getAnio()));
        lblMotor1.setText(vehiculo.getMotor());
        lblPlaca1.setText(vehiculo.getPlaca());
        String ruta = vehiculo.getImagen();
        lblImagen1.setIcon(traerImagen(ruta));
    }
    
    public void cargarDatos2(Vehiculo vehiculo){
        lblNombre2.setText(vehiculo.getNombre());
        lblMarca2.setText(vehiculo.getMarca());
        lblModelo2.setText(vehiculo.getModelo());
        lblPrecio2.setText(String.valueOf("LSP " + vehiculo.getPrecio()));
        lblAnio2.setText(String.valueOf(vehiculo.getAnio()));
        lblMotor2.setText(vehiculo.getMotor());
        lblPlaca2.setText(vehiculo.getPlaca());
        String ruta = vehiculo.getImagen();
        lblImagen2.setIcon(traerImagen(ruta));
    }
    
    public void cargarDatos3(Vehiculo vehiculo){
        lblNombre3.setText(vehiculo.getNombre());
        lblMarca3.setText(vehiculo.getMarca());
        lblModelo3.setText(vehiculo.getModelo());
        lblPrecio3.setText(String.valueOf("LSP " + vehiculo.getPrecio()));
        lblAnio3.setText(String.valueOf(vehiculo.getAnio()));
        lblMotor3.setText(vehiculo.getMotor());
        lblPlaca3.setText(vehiculo.getPlaca());
        String ruta = vehiculo.getImagen();
        lblImagen3.setIcon(traerImagen(ruta));
    }
    
    public double calculoPrecio(double preciobd, int anio){
        if(anio <= (LocalDate.now().getYear() - 10)){
            double descuento = preciobd * 0.3;
            return preciobd - descuento;
        }else{
            if(anio <= (LocalDate.now().getYear() - 5)){
                double descuento = preciobd * 0.1;
                return preciobd - descuento;
            }else{
                if(anio <= (LocalDate.now().getYear() - 1)){
                    double descuento = preciobd * 0.05;
                    return preciobd - descuento;
                }else{
                    return preciobd;
                }
            }
        }
    }
    
    public Icon traerImagen(String ruta){
        ImageIcon imagen1 = new ImageIcon(getClass().getResource(ruta));
        ImageIcon icon1 = new ImageIcon(imagen1.getImage().getScaledInstance(lblImagen1.getWidth(), lblImagen1.getHeight(), Image.SCALE_DEFAULT));
        return icon1;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblBMW = new javax.swing.JPanel();
        lblImagen1 = new javax.swing.JLabel();
        lblName1 = new javax.swing.JLabel();
        lblModel1 = new javax.swing.JLabel();
        lblBrand1 = new javax.swing.JLabel();
        lblPrice1 = new javax.swing.JLabel();
        lblNombre1 = new javax.swing.JLabel();
        lblMarca1 = new javax.swing.JLabel();
        lblModelo1 = new javax.swing.JLabel();
        lblPrecio1 = new javax.swing.JLabel();
        lblYear1 = new javax.swing.JLabel();
        lblmotor1 = new javax.swing.JLabel();
        lblKey1 = new javax.swing.JLabel();
        lblAnio1 = new javax.swing.JLabel();
        lblMotor1 = new javax.swing.JLabel();
        lblPlaca1 = new javax.swing.JLabel();
        btnVer1 = new javax.swing.JButton();
        lblBMW1 = new javax.swing.JPanel();
        lblImagen2 = new javax.swing.JLabel();
        lblName2 = new javax.swing.JLabel();
        lblModel2 = new javax.swing.JLabel();
        lblBrand2 = new javax.swing.JLabel();
        lblPrice2 = new javax.swing.JLabel();
        lblNombre2 = new javax.swing.JLabel();
        lblMarca2 = new javax.swing.JLabel();
        lblModelo2 = new javax.swing.JLabel();
        lblPrecio2 = new javax.swing.JLabel();
        lblYear2 = new javax.swing.JLabel();
        lblmotor2 = new javax.swing.JLabel();
        lblKey2 = new javax.swing.JLabel();
        lblAnio2 = new javax.swing.JLabel();
        lblMotor2 = new javax.swing.JLabel();
        lblPlaca2 = new javax.swing.JLabel();
        btnVer2 = new javax.swing.JButton();
        lblBMW2 = new javax.swing.JPanel();
        lblImagen3 = new javax.swing.JLabel();
        lblName3 = new javax.swing.JLabel();
        lblModel3 = new javax.swing.JLabel();
        lblBrand3 = new javax.swing.JLabel();
        lblPrice3 = new javax.swing.JLabel();
        lblNombre3 = new javax.swing.JLabel();
        lblMarca3 = new javax.swing.JLabel();
        lblModelo3 = new javax.swing.JLabel();
        lblPrecio3 = new javax.swing.JLabel();
        lblYear3 = new javax.swing.JLabel();
        lblmotor3 = new javax.swing.JLabel();
        lblKey3 = new javax.swing.JLabel();
        lblAnio3 = new javax.swing.JLabel();
        lblMotor3 = new javax.swing.JLabel();
        lblPlaca3 = new javax.swing.JLabel();
        btnVer3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblBMW.setBackground(new java.awt.Color(241, 238, 238));

        lblImagen1.setBackground(new java.awt.Color(255, 255, 255));
        lblImagen1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImagen1.setText("Imagen 1");

        lblName1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblName1.setText("Nombre: ");

        lblModel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblModel1.setText("Modelo: ");

        lblBrand1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblBrand1.setText("Marca: ");

        lblPrice1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblPrice1.setText("Precio: ");

        lblNombre1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblNombre1.setText("jLabel1");

        lblMarca1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblMarca1.setText("jLabel2");

        lblModelo1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblModelo1.setText("jLabel3");

        lblPrecio1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblPrecio1.setText("jLabel1");

        lblYear1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblYear1.setText("Año: ");

        lblmotor1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblmotor1.setText("Motor: ");

        lblKey1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblKey1.setText("Placa: ");

        lblAnio1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblAnio1.setText("jLabel1");

        lblMotor1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblMotor1.setText("jLabel2");

        lblPlaca1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblPlaca1.setText("jLabel3");

        btnVer1.setBackground(new java.awt.Color(153, 153, 153));
        btnVer1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnVer1.setText("Ver");

        javax.swing.GroupLayout lblBMWLayout = new javax.swing.GroupLayout(lblBMW);
        lblBMW.setLayout(lblBMWLayout);
        lblBMWLayout.setHorizontalGroup(
            lblBMWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblBMWLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(lblImagen1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addGroup(lblBMWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblName1)
                    .addComponent(lblModel1)
                    .addComponent(lblBrand1)
                    .addComponent(lblPrice1))
                .addGap(39, 39, 39)
                .addGroup(lblBMWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNombre1)
                    .addComponent(lblMarca1)
                    .addComponent(lblModelo1)
                    .addComponent(lblPrecio1))
                .addGap(178, 178, 178)
                .addGroup(lblBMWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblYear1)
                    .addComponent(lblmotor1)
                    .addComponent(lblKey1))
                .addGap(32, 32, 32)
                .addGroup(lblBMWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lblBMWLayout.createSequentialGroup()
                        .addComponent(lblAnio1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(lblBMWLayout.createSequentialGroup()
                        .addGroup(lblBMWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPlaca1)
                            .addComponent(lblMotor1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                        .addComponent(btnVer1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78))))
        );
        lblBMWLayout.setVerticalGroup(
            lblBMWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblBMWLayout.createSequentialGroup()
                .addGroup(lblBMWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lblBMWLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(lblBMWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnVer1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(lblBMWLayout.createSequentialGroup()
                                .addGroup(lblBMWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblName1)
                                    .addComponent(lblNombre1)
                                    .addComponent(lblYear1)
                                    .addComponent(lblAnio1))
                                .addGap(18, 18, 18)
                                .addGroup(lblBMWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblBrand1)
                                    .addComponent(lblMarca1)
                                    .addComponent(lblmotor1)
                                    .addComponent(lblMotor1))
                                .addGap(18, 18, 18)
                                .addGroup(lblBMWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblModel1)
                                    .addComponent(lblModelo1)
                                    .addComponent(lblKey1)
                                    .addComponent(lblPlaca1))
                                .addGap(29, 29, 29)
                                .addGroup(lblBMWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblPrice1)
                                    .addComponent(lblPrecio1)))))
                    .addGroup(lblBMWLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(lblImagen1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        lblBMW1.setBackground(new java.awt.Color(241, 238, 238));

        lblImagen2.setBackground(new java.awt.Color(255, 255, 255));
        lblImagen2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImagen2.setText("Imagen 2");

        lblName2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblName2.setText("Nombre: ");

        lblModel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblModel2.setText("Modelo: ");

        lblBrand2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblBrand2.setText("Marca: ");

        lblPrice2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblPrice2.setText("Precio: ");

        lblNombre2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblNombre2.setText("jLabel1");

        lblMarca2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblMarca2.setText("jLabel2");

        lblModelo2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblModelo2.setText("jLabel3");

        lblPrecio2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblPrecio2.setText("jLabel1");

        lblYear2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblYear2.setText("Año: ");

        lblmotor2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblmotor2.setText("Motor: ");

        lblKey2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblKey2.setText("Placa: ");

        lblAnio2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblAnio2.setText("jLabel1");

        lblMotor2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblMotor2.setText("jLabel2");

        lblPlaca2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblPlaca2.setText("jLabel3");

        btnVer2.setBackground(new java.awt.Color(153, 153, 153));
        btnVer2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnVer2.setText("Ver");

        javax.swing.GroupLayout lblBMW1Layout = new javax.swing.GroupLayout(lblBMW1);
        lblBMW1.setLayout(lblBMW1Layout);
        lblBMW1Layout.setHorizontalGroup(
            lblBMW1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblBMW1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(lblImagen2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addGroup(lblBMW1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblName2)
                    .addComponent(lblModel2)
                    .addComponent(lblBrand2)
                    .addComponent(lblPrice2))
                .addGap(39, 39, 39)
                .addGroup(lblBMW1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNombre2)
                    .addComponent(lblMarca2)
                    .addComponent(lblModelo2)
                    .addComponent(lblPrecio2))
                .addGap(178, 178, 178)
                .addGroup(lblBMW1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblYear2)
                    .addComponent(lblmotor2)
                    .addComponent(lblKey2))
                .addGap(32, 32, 32)
                .addGroup(lblBMW1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lblBMW1Layout.createSequentialGroup()
                        .addComponent(lblAnio2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(lblBMW1Layout.createSequentialGroup()
                        .addGroup(lblBMW1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPlaca2)
                            .addComponent(lblMotor2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVer2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78))))
        );
        lblBMW1Layout.setVerticalGroup(
            lblBMW1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblBMW1Layout.createSequentialGroup()
                .addGroup(lblBMW1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lblBMW1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(lblBMW1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblName2)
                            .addComponent(lblNombre2)
                            .addComponent(lblYear2)
                            .addComponent(lblAnio2))
                        .addGroup(lblBMW1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(lblBMW1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(lblBMW1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblBrand2)
                                    .addComponent(lblMarca2)
                                    .addComponent(lblmotor2)
                                    .addComponent(lblMotor2))
                                .addGap(18, 18, 18)
                                .addGroup(lblBMW1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblModel2)
                                    .addComponent(lblModelo2)
                                    .addComponent(lblKey2)
                                    .addComponent(lblPlaca2))
                                .addGap(29, 29, 29)
                                .addGroup(lblBMW1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblPrice2)
                                    .addComponent(lblPrecio2)))
                            .addGroup(lblBMW1Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(btnVer2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(lblBMW1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(lblImagen2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        lblBMW2.setBackground(new java.awt.Color(241, 238, 238));

        lblImagen3.setBackground(new java.awt.Color(255, 255, 255));
        lblImagen3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImagen3.setText("Imagen 2");

        lblName3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblName3.setText("Nombre: ");

        lblModel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblModel3.setText("Modelo: ");

        lblBrand3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblBrand3.setText("Marca: ");

        lblPrice3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblPrice3.setText("Precio: ");

        lblNombre3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblNombre3.setText("jLabel1");

        lblMarca3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblMarca3.setText("jLabel2");

        lblModelo3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblModelo3.setText("jLabel3");

        lblPrecio3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblPrecio3.setText("jLabel1");

        lblYear3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblYear3.setText("Año: ");

        lblmotor3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblmotor3.setText("Motor: ");

        lblKey3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblKey3.setText("Placa: ");

        lblAnio3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblAnio3.setText("jLabel1");

        lblMotor3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblMotor3.setText("jLabel2");

        lblPlaca3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblPlaca3.setText("jLabel3");

        btnVer3.setBackground(new java.awt.Color(153, 153, 153));
        btnVer3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnVer3.setText("Ver");

        javax.swing.GroupLayout lblBMW2Layout = new javax.swing.GroupLayout(lblBMW2);
        lblBMW2.setLayout(lblBMW2Layout);
        lblBMW2Layout.setHorizontalGroup(
            lblBMW2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblBMW2Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(lblImagen3, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addGroup(lblBMW2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblName3)
                    .addComponent(lblModel3)
                    .addComponent(lblBrand3)
                    .addComponent(lblPrice3))
                .addGap(39, 39, 39)
                .addGroup(lblBMW2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNombre3)
                    .addComponent(lblMarca3)
                    .addComponent(lblModelo3)
                    .addComponent(lblPrecio3))
                .addGap(178, 178, 178)
                .addGroup(lblBMW2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblYear3)
                    .addComponent(lblmotor3)
                    .addComponent(lblKey3))
                .addGap(32, 32, 32)
                .addGroup(lblBMW2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lblBMW2Layout.createSequentialGroup()
                        .addComponent(lblAnio3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(lblBMW2Layout.createSequentialGroup()
                        .addGroup(lblBMW2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPlaca3)
                            .addComponent(lblMotor3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                        .addComponent(btnVer3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78))))
        );
        lblBMW2Layout.setVerticalGroup(
            lblBMW2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblBMW2Layout.createSequentialGroup()
                .addGroup(lblBMW2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lblBMW2Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(lblBMW2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnVer3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(lblBMW2Layout.createSequentialGroup()
                                .addGroup(lblBMW2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblName3)
                                    .addComponent(lblNombre3)
                                    .addComponent(lblYear3)
                                    .addComponent(lblAnio3))
                                .addGap(18, 18, 18)
                                .addGroup(lblBMW2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblBrand3)
                                    .addComponent(lblMarca3)
                                    .addComponent(lblmotor3)
                                    .addComponent(lblMotor3))
                                .addGap(18, 18, 18)
                                .addGroup(lblBMW2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblModel3)
                                    .addComponent(lblModelo3)
                                    .addComponent(lblKey3)
                                    .addComponent(lblPlaca3))
                                .addGap(29, 29, 29)
                                .addGroup(lblBMW2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblPrice3)
                                    .addComponent(lblPrecio3)))))
                    .addGroup(lblBMW2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(lblImagen3, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblBMW2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblBMW, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblBMW1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(65, 65, 65))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(lblBMW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblBMW1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblBMW2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCatalogoVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCatalogoVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCatalogoVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCatalogoVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCatalogoVehiculos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVer1;
    private javax.swing.JButton btnVer2;
    private javax.swing.JButton btnVer3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAnio1;
    private javax.swing.JLabel lblAnio2;
    private javax.swing.JLabel lblAnio3;
    private javax.swing.JPanel lblBMW;
    private javax.swing.JPanel lblBMW1;
    private javax.swing.JPanel lblBMW2;
    private javax.swing.JLabel lblBrand1;
    private javax.swing.JLabel lblBrand2;
    private javax.swing.JLabel lblBrand3;
    private javax.swing.JLabel lblImagen1;
    private javax.swing.JLabel lblImagen2;
    private javax.swing.JLabel lblImagen3;
    private javax.swing.JLabel lblKey1;
    private javax.swing.JLabel lblKey2;
    private javax.swing.JLabel lblKey3;
    private javax.swing.JLabel lblMarca1;
    private javax.swing.JLabel lblMarca2;
    private javax.swing.JLabel lblMarca3;
    private javax.swing.JLabel lblModel1;
    private javax.swing.JLabel lblModel2;
    private javax.swing.JLabel lblModel3;
    private javax.swing.JLabel lblModelo1;
    private javax.swing.JLabel lblModelo2;
    private javax.swing.JLabel lblModelo3;
    private javax.swing.JLabel lblMotor1;
    private javax.swing.JLabel lblMotor2;
    private javax.swing.JLabel lblMotor3;
    private javax.swing.JLabel lblName1;
    private javax.swing.JLabel lblName2;
    private javax.swing.JLabel lblName3;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JLabel lblNombre2;
    private javax.swing.JLabel lblNombre3;
    private javax.swing.JLabel lblPlaca1;
    private javax.swing.JLabel lblPlaca2;
    private javax.swing.JLabel lblPlaca3;
    private javax.swing.JLabel lblPrecio1;
    private javax.swing.JLabel lblPrecio2;
    private javax.swing.JLabel lblPrecio3;
    private javax.swing.JLabel lblPrice1;
    private javax.swing.JLabel lblPrice2;
    private javax.swing.JLabel lblPrice3;
    private javax.swing.JLabel lblYear1;
    private javax.swing.JLabel lblYear2;
    private javax.swing.JLabel lblYear3;
    private javax.swing.JLabel lblmotor1;
    private javax.swing.JLabel lblmotor2;
    private javax.swing.JLabel lblmotor3;
    // End of variables declaration//GEN-END:variables
}
