/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hn.uth.pa1.parcial2.tarea2.app;

import hn.uth.pa1.parcial2.tarea2.app.objetos.Vehiculo;
import java.awt.Image;
import java.time.LocalDate;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author Miriam
 */
public class FrmDetallesVehiculo extends javax.swing.JFrame {

    /**
     * Creates new form FrmDetallesVehiculo
     */
    public FrmDetallesVehiculo() {
        initComponents();
    }
    
    public FrmDetallesVehiculo(Vehiculo vehiculo) {
        initComponents();
        lblNota.setText("<html>El cálculo del valor actual es proporcional al año del vehículo:<P>"
                + "<html>Mayor de 1 año se reduce un 5% del precio<P>"
                + "<html>Mayor de 5 años se reduce un 10% del precio<P>"
                + "<html>Mayor de 10 año se reduce un 30% del precio<P>");
        lblNombre.setText(vehiculo.getNombre());
        lblMarca.setText(vehiculo.getMarca());
        lblModelo.setText(vehiculo.getModelo());
        lblPrecio.setText(String.valueOf("LSP " + vehiculo.getPrecio()));
        lblAnio.setText(String.valueOf(vehiculo.getAnio()));
        lblMotor.setText(vehiculo.getMotor());
        lblPlaca.setText(vehiculo.getPlaca());
        lblPrecio.setText(String.valueOf(vehiculo.getPrecio()));
        double precio = calculoPrecio(vehiculo.getPrecio(), vehiculo.getAnio());
        lblDescripcion.setText(vehiculo.getDescripcion());
        lblValor.setText(String.valueOf("LPS " + precio));
        if((LocalDate.now().getYear() - vehiculo.getAnio()) == 1){
            lblAnios.setText(" el vehículo tiene 1 año");
        }else {
            
            lblAnios.setText(" el vehículo tiene " + (LocalDate.now().getYear() - vehiculo.getAnio()) + " años");
        }
        String ruta = vehiculo.getImagen();
        try {
            lblImagen.setIcon(traerImagen(ruta));
        } catch (Exception e) {
            lblImagen.setIcon(traerImagen("/Imagenes/ImageNotFound.jpg"));
        }
    }
    
    public Icon traerImagen(String ruta){
        ImageIcon imagen1 = new ImageIcon(getClass().getResource(ruta));
        ImageIcon icon1 = new ImageIcon(imagen1.getImage().getScaledInstance(lblImagen.getWidth(), lblImagen.getHeight(), Image.SCALE_DEFAULT));
        return icon1;
    }
    
    public double calculoPrecio(double preciobd, int anio){
        if(anio <= (LocalDate.now().getYear() - 10)){
            double descuento = preciobd * 0.3;
            return preciobd - descuento;
        }else{
            if(anio <= (LocalDate.now().getYear() - 5)){
                double descuento = preciobd * 0.1;
                return preciobd - descuento;
            }else{
                if(anio <= (LocalDate.now().getYear() - 1)){
                    double descuento = preciobd * 0.05;
                    return preciobd - descuento;
                }else{
                    return preciobd;
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblImagen = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblBrand = new javax.swing.JLabel();
        lblModel = new javax.swing.JLabel();
        lblYear = new javax.swing.JLabel();
        lblmotor = new javax.swing.JLabel();
        lblKey = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        lblDescription = new javax.swing.JLabel();
        lblMarca = new javax.swing.JLabel();
        lblModelo = new javax.swing.JLabel();
        lblAnio = new javax.swing.JLabel();
        lblMotor = new javax.swing.JLabel();
        lblPlaca = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        lblValorActual = new javax.swing.JLabel();
        lblValor = new javax.swing.JLabel();
        lblAnios = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        lblDescripcion = new javax.swing.JLabel();
        lblNote = new javax.swing.JLabel();
        lblNota = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();

        setTitle("Detalles del Vehículo");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(237, 235, 235));

        lblImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImagen.setText("Imagen");

        lblNombre.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblNombre.setText("Nombre");

        lblBrand.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblBrand.setText("Marca: ");

        lblModel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblModel.setText("Modelo: ");

        lblYear.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblYear.setText("Año:");

        lblmotor.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblmotor.setText("Motor: ");

        lblKey.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblKey.setText("Placa: ");

        lblPrice.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblPrice.setText("Precio: ");

        lblDescription.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblDescription.setText("Descripción: ");

        lblMarca.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblMarca.setText("jLabel1");

        lblModelo.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblModelo.setText("jLabel2");

        lblAnio.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblAnio.setText("jLabel3");

        lblMotor.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblMotor.setText("jLabel4");

        lblPlaca.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblPlaca.setText("jLabel5");

        lblPrecio.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblPrecio.setText("jLabel6");

        lblValorActual.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblValorActual.setText("Valor Actual: ");

        lblValor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblValor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblValor.setText("jLabel2");

        lblAnios.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblAnios.setText("jLabel3");

        btnRegresar.setBackground(new java.awt.Color(204, 204, 204));
        btnRegresar.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        lblDescripcion.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblDescripcion.setText("jLabel1");
        lblDescripcion.setToolTipText("");
        lblDescripcion.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lblNote.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblNote.setText("Nota:");

        lblNota.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblNota.setText("jLabel1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblNote)
                .addGap(36, 36, 36)
                .addComponent(lblNota, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(131, 131, 131))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addComponent(lblValorActual)
                                .addGap(46, 46, 46)
                                .addComponent(lblValor, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDescription)
                                    .addComponent(lblNombre)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblBrand)
                                            .addComponent(lblModel)
                                            .addComponent(lblYear)
                                            .addComponent(lblmotor)
                                            .addComponent(lblKey)
                                            .addComponent(lblPrice))
                                        .addGap(61, 61, 61)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(lblMarca, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                                                .addComponent(lblModelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lblAnio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lblMotor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lblPlaca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(lblPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(lblDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(lblAnios))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(350, 350, 350)
                        .addComponent(btnRegresar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(lblNombre)
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBrand)
                            .addComponent(lblMarca))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblModel)
                            .addComponent(lblModelo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblYear)
                            .addComponent(lblAnio))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblmotor)
                            .addComponent(lblMotor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblKey)
                            .addComponent(lblPlaca))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPrice)
                            .addComponent(lblPrecio))
                        .addGap(18, 18, 18)
                        .addComponent(lblDescription)
                        .addGap(18, 18, 18)
                        .addComponent(lblDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValorActual)
                    .addComponent(lblValor)
                    .addComponent(lblAnios))
                .addGap(59, 59, 59)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNota)
                    .addComponent(lblNote))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        lblTitulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTitulo.setText("Vista de Vehículo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(lblTitulo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(136, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDetallesVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDetallesVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDetallesVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDetallesVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmDetallesVehiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblAnio;
    private javax.swing.JLabel lblAnios;
    private javax.swing.JLabel lblBrand;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblKey;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblModel;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblMotor;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNota;
    private javax.swing.JLabel lblNote;
    private javax.swing.JLabel lblPlaca;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblValor;
    private javax.swing.JLabel lblValorActual;
    private javax.swing.JLabel lblYear;
    private javax.swing.JLabel lblmotor;
    // End of variables declaration//GEN-END:variables
}
