/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hn.uth.pa1.parcial2.tarea2.app;

import hn.uth.pa1.parcial2.tarea2.app.objetos.Vehiculo;
import java.util.List;

/**
 *
 * @author Miriam
 */
public class PanPreviaVehiculo extends javax.swing.JPanel {

    /**
     * Creates new form PanPreviaVehiculo
     */
    
    public static List<Vehiculo> vehiculos = FrmCatalogoVehiculos1.vehiculos;
    
    public PanPreviaVehiculo() {
        initComponents();
        lblNombre.setText(vehiculo.getNombre());
        lblMarca.setText(vehiculo.getMarca());
        lblModelo.setText(vehiculo.getModelo());
        lblPrecio.setText(String.valueOf(vehiculo.getPrecio()));
        lblAnio.setText(String.valueOf(vehiculo.getAnio()));
        lblMotor.setText(vehiculo.getMotor());
        lblPlaca.setText(vehiculo.getPlaca());
        panImagenVehiculo.setVisible(false);
        panImagenVehiculo.setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombre1 = new javax.swing.JLabel();
        lblMarca1 = new javax.swing.JLabel();
        lblModelo1 = new javax.swing.JLabel();
        lblPrecio1 = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblMarca = new javax.swing.JLabel();
        lblModelo = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        lblAnio1 = new javax.swing.JLabel();
        lblMotor1 = new javax.swing.JLabel();
        lblPlaca1 = new javax.swing.JLabel();
        lblAnio = new javax.swing.JLabel();
        lblMotor = new javax.swing.JLabel();
        lblPlaca = new javax.swing.JLabel();
        btnVer = new javax.swing.JButton();
        panImagenVehiculo = new javax.swing.JPanel();

        lblNombre1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNombre1.setText("Nombre: ");

        lblMarca1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMarca1.setText("Marca: ");

        lblModelo1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblModelo1.setText("Modelo: ");

        lblPrecio1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPrecio1.setText("Precio: ");

        lblNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNombre.setText("Uwu");

        lblMarca.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMarca.setText("Uwu");

        lblModelo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblModelo.setText("Uwu");

        lblPrecio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPrecio.setText("Uwu");

        lblAnio1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblAnio1.setText("Año: ");

        lblMotor1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMotor1.setText("Motor: ");

        lblPlaca1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPlaca1.setText("Placa: ");

        lblAnio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblAnio.setText("Uwu");

        lblMotor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMotor.setText("Uwu");

        lblPlaca.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPlaca.setText("Uwu");

        btnVer.setBackground(new java.awt.Color(204, 204, 204));
        btnVer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnVer.setText("Ver");
        btnVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerActionPerformed(evt);
            }
        });

        panImagenVehiculo.setBackground(new java.awt.Color(255, 255, 255));
        panImagenVehiculo.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                panImagenVehiculoComponentShown(evt);
            }
        });

        javax.swing.GroupLayout panImagenVehiculoLayout = new javax.swing.GroupLayout(panImagenVehiculo);
        panImagenVehiculo.setLayout(panImagenVehiculoLayout);
        panImagenVehiculoLayout.setHorizontalGroup(
            panImagenVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 245, Short.MAX_VALUE)
        );
        panImagenVehiculoLayout.setVerticalGroup(
            panImagenVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 187, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(panImagenVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMarca1)
                    .addComponent(lblNombre1)
                    .addComponent(lblModelo1)
                    .addComponent(lblPrecio1))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPrecio)
                    .addComponent(lblModelo)
                    .addComponent(lblNombre)
                    .addComponent(lblMarca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMotor1)
                    .addComponent(lblPlaca1)
                    .addComponent(lblAnio1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblAnio)
                        .addComponent(lblPlaca))
                    .addComponent(lblMotor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78)
                .addComponent(btnVer, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(btnVer, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblAnio1)
                                    .addComponent(lblAnio))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblMotor1)
                                    .addComponent(lblMotor))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblPlaca1)
                                    .addComponent(lblPlaca)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblNombre1)
                                    .addComponent(lblNombre))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblMarca1)
                                    .addComponent(lblMarca))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblModelo1)
                                    .addComponent(lblModelo))))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPrecio1)
                            .addComponent(lblPrecio)))
                    .addComponent(panImagenVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleParent(this);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnVerActionPerformed

    private void panImagenVehiculoComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_panImagenVehiculoComponentShown
        // TODO add your handling code here:
        PanImagen im = new PanImagen(panImagenVehiculo);
        panImagenVehiculo.add(im);
        panImagenVehiculo.revalidate();
        panImagenVehiculo.repaint();
    }//GEN-LAST:event_panImagenVehiculoComponentShown


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVer;
    private javax.swing.JLabel lblAnio;
    private javax.swing.JLabel lblAnio1;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblMarca1;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblModelo1;
    private javax.swing.JLabel lblMotor;
    private javax.swing.JLabel lblMotor1;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JLabel lblPlaca;
    private javax.swing.JLabel lblPlaca1;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblPrecio1;
    public javax.swing.JPanel panImagenVehiculo;
    // End of variables declaration//GEN-END:variables
}
